name: data-science-torch
channels:
  - conda-forge
  - nvidia
  - pytorch
  - defaults
dependencies:
  - python=3.11
  - nvidia::cudatoolkit
  - pytorch::pytorch
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - jupyterlab
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit  # Only include if you have a compatible GPU
  - pip
  - pip:
      - jupyter_contrib_nbextensions
      - ipywidgets
      - flask
      - gunicorn
      - transformers
      - ibm-watsonx-ai
      - notebook
      - tensorflow
      - accelerate